theme: jekyll-theme-slate
title: Descobrindo o Caos nos Números
description: Registro histórico-técnico do fenômeno espectral na aritmética.
show_downloads: true
google_analytics: # Deixe vazio por enquanto
